---

- name: Ansible playbook for configuring media
  hosts: media
  roles:
    - media
      #    - role:  caddy_ansible.caddy_ansible
      #caddy_update: true
      #caddy_environment_variables:
      #  CF_API_TOKEN: lookup('community.general.bitwarden', '4dff3ba8-f509-420e-b370-b06201165d99', search='id', field='notes') | first
      #caddy_systemd_capabilities_enabled: true
      #caddy_systemd_network_dependency: false
      #caddy_packages: ["github.com/caddy-dns/cloudflare"]
      #caddy_config: |
      #  tls {
      #    acme_dns cloudflare {env.CF_API_TOKEN}
      #  }
      #  sonarr.media.internal.craftcat.dev {
      #    reverse_proxy http://192.168.1.182:8989  
      #  }
  remote_user: root

