---

- name: Ansible playbook for configuring media
  hosts: media
  roles:
    - media
    - role: caddy-ansible
      caddy_update: true
      caddy_systemd_capabilities_enabled: true
      caddy_systemd_network_dependency: false
      caddy_packages: ["github.com/caddy-dns/cloudflare"]
      caddy_config: |
        (cloudflare) {
          tls {
            dns cloudflare {{ lookup('community.general.bitwarden', '4dff3ba8-f509-420e-b370-b06201165d99', search='id', field='notes') | first }}
          }
        }
        sonarr.media.internal.craftcat.dev {
          reverse_proxy http://192.168.1.182:8989  
          import cloudflare
        }
        prowlarr.media.internal.craftcat.dev {
          import cloudflare
          reverse_proxy http://192.168.1.182:9696
        }
  remote_user: root

